version: '3'

interval: 500ms

tasks:
  build:
    sources:
      - go.mod
      - main.go
      - Dockerfile
    cmds:
      - docker compose build

  up:
    deps:
      - task: build
    cmds:
      - docker compose up