version: '3'

interval: 5s

tasks:
  dev:
    sources:
      - go.mod
      - main.go
    cmds:
      - killall -9 app || true
      - go mod tidy
      - go build -o app && ./app

  build:
    cmds:
      - docker compose build

  up:
    deps:
      - task: build
    cmds:
      - docker compose up